---
title:                                  Amplitude
title_extention:                        Custom Audio Player
tagline:                                Custom Audio Player

date:                                   2024-04-17
#last_modified:                         2024-01-01

description: >
                                        AmplitudeJS is a JavaScript library to control the design
                                        of audio media players on web pages. The concept allows
                                        designers to fully control the look and feel of players
                                        without deep scripting knowledge.
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap, html, html5, audio,
                                        AmplitudeJS, Amplitude

categories:                             [ Previewer ]
tags:                                   [ Amplitude, Audio ]

image:
  path:                                 /assets/image/icons/videojs/videojs-poster.png
  width:                                1920
  height:                               1280

regenerate:                             true
personalization:                        true
permalink:                              /pages/public/tools/previewer/amplitudejs/

resources:                              [ amplitudejs ]
resource_options:
  - toccer:
      collapseDepth:                    2
  - attic:
      slides:
        - url:                          /assets/image/modules/attics/1920x1280/alexey-ruban.jpg
          alt:                          Photo by Alexey Ruban on Unsplash
          badge:
            type:                       unsplash
            author:                     Alexey Ruban
            href:                       //unsplash.com/de/@intelligenciya
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// See: https://521dimensions.com/open-source/amplitudejs/docs
// See: https://github.com/mediaelement/mediaelement-plugins
// See: https://github.com/serversideup/amplitudejs/

[role="dropcap"]
The Audio tag in HTML5 is a great way to add audio media to web pages.
However, the browser fully controls the audio playback interface,
which can limit or even break a page's design if audio media is used.

AmplitudeJS for the J1 Template offers a straightforward solution for web
developers. It allows them to easily customize the appearance of their audio
players without the need for complex scripting. By leveraging J1 Template
and Amplitude's API, web designers can craft unique interfaces that define
the visual and functional aspects of a player's audio control elements.

mdi:clock-time-five-outline[24px, md-gray mr-2]
*5-10 Minutes* to read

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
// include::{documentdir}/amplitudejs.compact.css.asciidoc[]
// include::{documentdir}/amplitudejs.large.css.asciidoc[]
// include::{documentdir}/amplitudejs.mini.css.asciidoc[]

[role="mt-4"]
The J1 Template implements custom players based on the (default) theme Uno.
The color scheme used matches the look and feel of the template to preserve
the page design.

Three types of AmplitudeJS players are build-in for the J1 template system:

* Mini Player
* Compact Player (default player)
* Large Player

[role="mt-4"]
[NOTE]
====
Amplitude players for the J1 Template are mobile-friendly. Instead of
clicking on the appropriate elements, touch events are applied to all
mobile devices.
====


[role="mt-5"]
== Mini Player

In the context of complex components on a web page, like an audio player,
a mini player refers to a minimized version of full players. It typically
offers basic playback controls, such as pause, play, and
volume adjustment, while taking up less screen space.

Mini players are beneficial when you want to listen to audio in the
background without dedicating the entire screen to the player. They
are commonly found on music streaming services, podcast platforms, and
websites with embedded audio content.

.Emancipator · Dusk To Dawn
amplitude::free_emancipator_mini[role="mt-3 mb-5"]

.Royalty Free Music · Disco 80th
amplitude::free_disco_mini[role="mt-3 mb-5"]


[role="mt-5"]
== Compact Player

A complex component like an audio player on a web page, *compact*
typically refers to a design or layout that minimizes the component's
space while maintaining its functionality and usability.

The *compact* design allows the audio player to fit neatly within the web
page's layout without overwhelming or dominating the content around it.
The design aims to balance functionality and space efficiency, ensuring
users can easily access and control the audio playback without sacrificing
too much screen space.

.Emancipator · Dusk To Dawn
amplitude::free_emancipator_compact[role="mt-3 mb-5"]

.Royalty Free Music · Disco 80th
amplitude::free_disco_compact[role="mt-3 mb-5"]


[role="mt-5"]
== Large Player

A large player supports a design for displaying all components but requires
a webpage's full (horizontal) space. This player type makes it easy for all
users to navigate and playback all audio titles provided.

Large players are a good choice when only a seleted number of albums or
playlists should be placed on a page.

.Emancipator · Dusk To Dawn
amplitude::free_emancipator_large[role="mt-3 mb-5"]

.Royalty Free Music · Disco 80th
amplitude::free_disco_large[role="mt-3 mb-5"]

I hope, you've enjoyed exploring the possibilities J1 offers for playing
digital audio content. But much, much more can the J1 do for your web in
terms of multimedia.

[role="mb-7"]
Find more players focussing video plackback technologies on the page
link:{url-tour--playback-video}[Video Player].
