---
title:                                  Audio Player
title_extention:                        Playing Audio files
tagline:                                Playing Audio files

date:                                   2024-04-16
#last_modified:                         2024-01-01

description: >
                                        HTML 5 has brought sanity to audio support in the browser
                                        by adding the audio tag element and by introducing several
                                        standard audio formats.
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap, html, html5,
                                        asciidoctor, audio

categories:                             [ Tour ]
tags:                                   [ Audio, Module ]

image:
  path:                                 /assets/image/modules/attics/1920x1280/alexey-ruban.jpg
  width:                                1920
  height:                               1280

tts:                                    true
comments:                               false
exclude_from_search:                    false
regenerate:                             false
personalization:                        true
permalink:                              /pages/public/tour/present_audio/

resources:                              [ amplitudejs ]
resource_options:
  - toccer:
      collapseDepth:                    2
  - attic:
      slides:
        - url:                          /assets/image/modules/attics/1920x1280/alexey-ruban.jpg
          alt:                          Photo by Alexey Ruban on Unsplash
          badge:
            type:                       unsplash
            author:                     Alexey Ruban
            href:                       //unsplash.com/de/@intelligenciya
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:
:url-html-audio--plugin:                //localhost/pages/public/tour/present_audio/

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>


//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}

// See: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs
//
[role="dropcap"]
The Audio tag in HTML5 is a great way to add audio media to web pages.
However, the browser fully controls the audio playback interface,
which can limit or even break a page's design if audio media is used.

AmplitudeJS for J1 Template offers a straightforward solution for web
developers. It allows them to easily customize the appearance of their audio
players without the need for complex scripting. By leveraging J1 Template
and Amplitude's API, web designers can craft unique interfaces that define
the visual and functional aspects of a player's audio control elements.

mdi:clock-time-five-outline[24px, md-gray mt-4 mb-5 mr-2]
*5-10 Minutes* to read


// See: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs
// See: https://docs.asciidoctor.org/asciidoc/latest/macros/audio-and-video/
//
[role="mt-5"]
== HTML 5 Audio

Audio players can easily be embedded in web pages using the *audio* tag
`<audio>.` Browsers have a built-in framework for decoding and playing audio
content directly within a webpage.

.Ambient Piano
audio::/assets/audio/sound-effects/ambient-piano.mp3[role="mt-4 mb-5"]

The block audio macro `audio::` enables you to embed audio streams into your
documents. Using the macro, embed self-hosted audio files or audio sources
from the Internet are supported.

.Basic audio file include
[source, js]
----
audio::ambient-piano.mp3[]
----

You can control the audio settings using additional attributes on the
macro. For instance, you can offset the start time of playback using the
start attribute `start` and enable autoplay using the `autoplay` option.

.Set attributes for local audio playback
[source, js]
----
audio::mbient-pianov[start=60,opts=autoplay]
----

The native HTML5 <audio> element does not provide built-in functionality for
direct playlist playback. While it can play a single audio file, it does not
allow you to manage and control a sequence of audio data.

If playlist playback is required, see section <<AmplitudeJS Audio>> for more
powerful audio players available for J1 Template.



[role="mt-5"]
== AmplitudeJS Audio

The J1 Template implements custom players based on the (default) theme Uno.
The color scheme used matches the look and feel of the template to preserve
the page design.

Three types of AmplitudeJS players are build-in for the J1 template system:

* Mini Player
* Compact Player (default payer)
* Large Player

[role="mt-4"]
[NOTE]
====
Amplitude players for the J1 Template are mobile-friendly. Instead of
clicking on the appropriate elements, touch events are applied to all
mobile devices.
====


[role="mt-5"]
== Mini Player

In the context of complex components on a web page, like an audio player,
a mini player refers to a minimized version of full players. It typically
offers basic playback controls, such as pause, play, and
volume adjustment, while taking up less screen space.

Mini players are beneficial when you want to listen to audio in the
background without dedicating the entire screen to the player. They
are commonly found on music streaming services, podcast platforms, and
websites with embedded audio content.

.Emancipator · From Dusk To Dawn
amplitude::free_emancipator_mini[role="mt-3 mb-5"]

.Royalty Free Music · Disco 80th
amplitude::free_disco_mini[role="mt-3 mb-5"]

lorem:sentences[5]

[role="mt-5"]
== Compact Player

A complex component like an audio player on a web page, *compact*
typically refers to a design or layout that minimizes the component's
space while maintaining its functionality and usability.

////
The *compact design* for an audio player is an efficient approach that
involves condensing the player controls and display elements into a smaller
area. It uses icons or symbols instead of text labels where possible, and
possibly hides less frequently used features behind menus or dropdowns to
reduce clutter, thereby instilling confidence in its effectiveness.

A *compact* design allows the audio player to fit neatly within the web
page's layout without overwhelming or dominating the content around it.
The design aims to balance functionality and space efficiency, ensuring
users can easily access and control the audio playback without sacrificing
too much screen space.
////

.Emancipator · From Dusk To Dawn
amplitude::free_emancipator_compact[role="mt-3 mb-5"]

.Royalty Free Music · Disco 80th
amplitude::free_disco_compact[role="mt-3 mb-5"]

lorem:sentences[5]


[role="mt-5"]
== Large Player

lorem:sentences[5]

.Emancipator · From Dusk To Dawn
amplitude::free_emancipator_large[role="mt-3 mb-5"]

.Royalty Free Music · Disco 80th
amplitude::free_disco_large[role="mt-3 mb-5"]

[role="mb-8"]
lorem:sentences[3]


[role="mt-5"]
== What next

I hope, you've enjoyed exploring the possibilities J1 offers for playing
digital audio content. But much, much more can the J1 do for your web in
terms of multimedia.

The J1 Template support playing video on web pages by using the
HTML5 video support, the new standard of HTML. HTML5 implements a
pure HTML way to show play video on the web. Modern browsers
support the the video tag `<video>` for the current HTML5 standard.

The previous proprietary de facto standard software like a Flash Player,
Quicktime, or Silverlight is no longer needed as the Theme JekyllOne provides
HTML5 video for local content and from online sources on the Internet.

[role="mb-7"]
Incredible? See the next example page link:{url-tour--present-video}[Video Player].
