---
title:                                  Amplitude YT Tester
title_extention:                        YT Video Integration
tagline:                                YT Video Integration

date:                                   2024-09-21
#last_modified:                         2024-01-01

description: >
                                        The J1 Template support playing video on web pages
                                        by HTML5 Video, the new standard of HTML to show
                                        videos on web pages.
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap,
                                        html, html5, video, support, flash player,
                                        quicktime, silverlight

categories:                             [ Roundtrip ]
tags:                                   [ Module, Video ]

image:
  path:                                 /assets/image/modules/attics/markus-spiske-1920x1280.jpg
  width:                                1920
  height:                               1280

attic:                                  false
regenerate:                             false
personalization:                        true
permalink:                              /pages/public/amplitude_yt_tester/

resources:                              [ amplitudejs ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/image/modules/attics/markus-spiske-1920x1280.jpg
          alt:                          Video Tester
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
The J1 Template support playing video on web pages by HTML5 Video, the new
standard of HTML to show videos on webpages.

Modern browsers support the video tag `<video>` for the new HTML5 video
standard. The previous proprietary de facto standard software like
_Flash Player_, _Quicktime_, or _Silverlight_ is no longer needed as the
Jekyll theme J1 provides HTML5 Video support for local video content
and from online sources on the Internet.

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-4"]
== YouTube Audio

// https://www.youtube.com/watch?v=7_WWz2DSnT8
//
// https://www.youtube.com/watch?v=WxcWO9O4DSM, 19:58, Tchaikovsky - Romeo and Juliet: Fantasy Overture
// https://www.youtube.com/watch?v=zAmDwCz2BOs
// https://www.youtube.com/watch?v=ryxAe4B_3Pg
// https://www.youtube.com/watch?v=wI1Rr29OCJM

You can embed any YouTube video in your web pages and visitors on your
site will be able to play and pause the video audio with a simple click.
With this technique, you can also use a YouTube video as background audio
that runs in a loop.

[TIP]
====
The audio player is created using the YouTube API. Read the full Tutorial at:
http://www.labnol.org/internet/youtube-audio-player/26740/[Embed YouTube as an Audio Player, {browser-window--new}]
====

[role="mt-4"]
=== How to Embed YouTube Audio

It takes just one step to embed a YouTube audio. Open any YouTube video
and make a note of the YouTube Video ID (a string of 11 characters).

Next copy-paste the code below anywhere on your website and replace
VIDEO_ID with actual ID of your YouTube video.

[source, html]
----
<div data-video="VIDEO_ID" data-autoplay="0" data-loop="1" id="youtube-audio"></div>
<script src="https://www.youtube.com/iframe_api"></script>
<script src="https://cdn.rawgit.com/labnol/files/master/yt.js"></script>
----

There are few other configuration parameters that you can change depending
on requirements. For instance, if you set data-autoplay to 1, the audio will
begin playing immediately on page load. Likewise, set data-loop to 1 and the
audio will play continuously in a never-ending loop until manually stopped.

This internally renders the YouTube video using the IFRAME player and would
thus work on both desktop and mobile browsers. The JavaScript files are hosted
on Github while the images are hosted on Imgur. It is recommended that you
copy the assets to your own server before deploying on a heavy-traffic website.

[role="mt-4"]
=== Technical Details

We are using the YouTube JavaScript API that renders a regular YouTube player
but with the width and height set to *0 pixels*. When the user clicks the
audio button, it toggles the existing YouTube player state and the video
begins to play or pauses.

Here’s the annotated version of the source code. It can be extended to embed
YouTube playlists, the default playback volume can be changed or you even
https://www.labnol.org/internet/embed-part-of-youtube-video/27948/[embeda part, {browser-window--new}]
of the video.

////
[role="mt-5"]
=== YT Player
++++
<!-- 1. The <iframe> (and video player) will replace this <div> tag.            -->
<!-- =========================================================================== -->
<div style="display:flex;justify-content:center;align-items:center;">
  <div id="youtube-audio1" data-video="WxcWO9O4DSM" data-autoplay="0" data-loop="1"></div>
  <div id="youtube-audio2" data-video="zAmDwCz2BOs" data-autoplay="0" data-loop="1"></div>
  <!-- div id="youtube-audio2"></div -->
  <div id="youtube-audio3" data-video="ryxAe4B_3Pg" data-autoplay="0" data-loop="1"></div>
  <div id="youtube-audio4" data-video="wI1Rr29OCJM" data-autoplay="0" data-loop="1"></div>
</div>
++++

++++
<script>
  $(function() {

    // Load the IFrame Player API code asynchronously.
    var techScript;

    var tech    = document.createElement('script');
    tech.src    = "/assets/theme/j1/modules/amplitudejs/js/tech/youtube.js";
    techScript  = document.getElementsByTagName('script')[0];

    techScript.parentNode.insertBefore(tech, techScript);

  });
</script>
++++
////

[role="mt-5"]
== Amplitude Player

lorem:sentences[5]

.Mimi Rutherfurt · Maritim Verlag (YouTube)
amplitude::mimi_rutherfurt_yt_large[role="mt-4 mb-8"]

++++
<script>
  $(function() {

    // Load the IFrame Player API code asynchronously.
    var techScript;

    var tech    = document.createElement('script');
    tech.src    = "/assets/theme/j1/modules/amplitudejs/js/tech/ytp.js";
    techScript  = document.getElementsByTagName('script')[0];

    techScript.parentNode.insertBefore(tech, techScript);

  });
</script>
++++
////
[[ms_video]]
== MS Slider using YouTube Video

lorem:sentences[5]

.Slider using Video
masterslider::ms_00010[role="mt-4 mb-5"]


[role="mt-5"]
== YouTube Video

YouTube is a popular online video-sharing platform that allows users to
upload, view, share, and comment on videos. The platform provides services
for people and organizations to publish various video content.

.Fortnight (feat. Post Malone, Official Music Video) · Taylor Swift
youtube::q3zqJs7JUCQ[poster="//img.youtube.com/vi/q3zqJs7JUCQ/maxresdefault.jpg" role="mt-4 mb-5"]


[role="mt-5"]
== Local Video

VideoJS provides a flexible and customizable platform for displaying and
controlling MPEG 4 video content on websites and web applications.

.Video over VideoJS
gallery::jg_video_html5_videojs[role="mt-4 mb-5"]
////
