---
title:                                  Themes
title_extention:                        Bootstrap V5 Themes
tagline:                                Individual Style

date:                                   2026-05-07
#last_modified:                         2026-01-01

description: >
                                        J1 Template offers various unique functionalities compared to other Jekyll themes and templates. Bootstrap themes for the J1 Template are based on the free and Open Source CSS front-end framework Bootstrap of version V5. The
                                        Bootstrap themes for the J1 enable the presentation of different versions (skins) of the same site using already prepared Bootstrap CSS templates.
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap,
                                        css, style, theme, skin

categories:                             [ Roundtrip ]
tags:                                   [ Bootstrap, Module, Theme ]

image:
  path:                                 /assets/image/module/attic/1920x1280/stories-ink-tattoo-care.jpg
  width:                                1920
  height:                               1280

regenerate:                             false
permalink:                              /pages/public/tour/themes/

resources:                              [ lightbox ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/image/module/attic/1920x1280/stories-ink-tattoo-care.jpg
          alt:                          Photo by Stories & Ink Tattoo Care on Unsplash
          badge:
            type:                       unsplash
            author:                     Stories & Ink Tattoo Care
            href:                       https://unsplash.com/de/@storiesandink
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:time-num--string:                      3
:time-en--string:                       Minutes
:time-en--description:                  to read
:time-de--string:                       Minuten
:time-de--description:                  Lesezeit

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Themes for the J1 Template are based on the Open Source CSS framework
*Bootstrap* (version 5). A theme is like a *skin* for your website -- it
changes the *look* of your pages without changing the content. With themes,
you can show the same site in many different styles.

A theme makes sure your website looks the same on every modern web browser.
It sets the colors, fonts, sizes, and the look of buttons, tables, and
forms. You can also use Bootstrap's built-in CSS classes to fine-tune
parts of your design on your own.

[subs=attributes]
++++
<div class="video-title">
  <i class="mdi mdi-gray mdi-clock-time-five-outline mdi-24px mr-2"></i>
  {time-num--string} {time-en--string} {time-en--description}.
</div>
++++

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== The Themes

A theme changes how your website *looks*, but not how it *works*. It uses
CSS rules from Bootstrap to set things like the color scheme, fonts, sizes,
and the appearance of more complex parts such as forms and tables. Some
themes also add extra components on top of the standard Bootstrap set.

Changing the CSS styles of link:{url-bs--home}[Bootstrap, {browser-window--new}]
is not too hard, but you do need some basic knowledge of
link:{url-w3org--css-spec}[CSS, {browser-window--new}] to do it well.
If you are new to CSS, the
link:{url-w3schools--css-tutorial}[CSS tutorial at W3Schools, {browser-window--new}]
is a good place to start. CSS is the design language used by every
modern website.

.Bootswatch Themes (Examples)
lightbox::bootswatch-themes[1280, {data-images--bootswatch-themes}]

Thanks to the team at link:{url-bootswatch--home}[Bootswatch, {browser-window--new}],
many ready-made Bootstrap stylesheets are available for free. You can use
them as they are, or use them as a starting point for your own design --
you do not have to build everything from scratch.

Bootswatch also offers an
link:{url-bootswatch--api}[Integration API, {browser-window--new}] that
makes it easy to add their themes to an existing site. The J1 Template
uses this API so you can pick a Bootswatch theme right from the menu of
your website.

[role="mt-4"]
=== Apply a Style

The default theme of the J1 Template is called *Uno*. It comes with both
a *light* and a *dark* version and works well for many kinds of websites.
*Uno* is a good starting point. If you want a different look, you can
combine *Uno* with another theme to get your site ready quickly.

You can find every available theme in the *Themes* menu in the top bar of
your website. Try a few of them and see how the page changes when a
different theme is used.

[WARNING]
====
When you switch from one theme to another *while the site is running*, the
J1 Template tries to apply the new styles to all parts of the page (such
as fonts, headings, lists, and paragraphs). This works for *most* common
elements, but *not yet* for every single one.
====

Pick a theme from the *Themes* menu, and the new Bootstrap stylesheet is
applied automatically to every page of your website.


[role="mt-5"]
== What next

The J1 Template is a great starting point for many kinds of websites.
One handy feature it offers is *code highlighting*. Code highlighting
adds colors to source code so it is easier to read and understand.

Each programming language has its own keywords and rules. Code highlighting
uses different colors for different parts of the code. For example, in
JavaScript, keywords like *if*, *for*, or *function* get one color, while
text strings and variables get another.

The J1 Template uses a code highlighter called *Rouge*. Rouge is written in
Ruby and supports more than 100 programming languages. It produces colored
HTML output that works in every modern web browser.

To see what Rouge can do, go to the
link:{url-tour--rouge-hightlighter}[Code Highlighter] page.
