---
title:                                  Advanced Modals
title_extention:                        Advanced Bootstrap V5 Modals for J1 Template
tagline:                                Best Visitor Experience for Your Web

date:                                   2026-05-07
#last_modified:                         2026-01-01

description: >
                                        J1 Template supports a rich set of advanced Bootstrap Modals
                                        that add dialogs to your web pages for user notifications.
                                        The advanced Modals highlight important information to your
                                        visitors. Modals are positioned over everything else in the
                                        document so that messages get the full user's attention.
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap,
                                        modals, advanced, extension

categories:                             [ Roundtrip ]
tags:                                   [ Bootstrap, Modal, Extension ]

image:
  path:                                 /assets/image/page/tour/bootstrap-1920x1000-bw.jpg
  width:                                1920
  height:                               1280

regenerate:                             false
permalink:                              /pages/public/tour/modals/

resources:                              []
resource_options:
  - attic:
      slides:
        - url:                          /assets/image/page/tour/bootstrap-1920x1000-bw.jpg
          alt:                          Bootstrap Framework Logo
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Attribute settings for page content control (e.g includes)
//
:documentdir:                           _includes/documents

// Attribute settings for page section control
//
:time-num--string:                      5-10
:time-en--string:                       Minutes
:time-en--description:                  to read
:time-de--string:                       Minuten
:time-de--description:                  Lesezeit

// Additiona page attributes
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
A *modal* is a small pop-up window that appears on top of a web page. It
is used to show important information, ask a question, or get a response
from the visitor. The J1 Template comes with a rich set of advanced
Bootstrap modals that you can drop into any page.

Because a modal appears on top of the page, the rest of the content is
dimmed. This focuses the visitor's attention on the message and makes
sure important information is not missed.

[subs=attributes]
++++
<div class="video-title">
  <i class="mdib mdib-clock-outline mdib-24px mr-2"></i>
  {time-num--string} {time-en--string} {time-en--description}
</div>
++++

// Include sub-documents (hidden content)
// -----------------------------------------------------------------------------
include::{documentdir}/419_advanced_modals_demo.asciidoc[]

[role="mt-5"]
== Modal Examples

Modals are a good way to draw your reader's attention to important
information. The J1 Template provides extra modal styles that match the
*tone* of the message -- from a friendly note to a serious warning. You
can pick a style that fits the importance of what you want to say:

* a calm *info* style for general notes,
* a *warning* style for things readers should be careful about,
* a *critical* style for messages that must not be missed.

[TIP]
====
For more details on how Bootstrap's modal plugin works, see the
link:{url-bs-docs--components-modal}[Bootstrap documentation, {browser-window--new}].
====

// Include sub-documents (table for BS Modal examples)
include::{documentdir}/410_table_bs_modal_examples.asciidoc[]


[role="mt-5"]
== What next

Bootstrap is a powerful framework for building responsive websites. But
even Bootstrap can be improved. One example is the way *tables* are
shown on small screens like phones and tablets.

The J1 Template adds a new design for *responsive tables*, built on top
of Bootstrap. The design uses simple CSS styles to make tables easy to
read on every device and browser. This is especially helpful for
visitors using mobile phones, where space is limited and standard
tables can be hard to read.

See for yourself what J1
link:{url-tour--responsive-tables}[Responsive Tables] can do!
