---
title:                                  Video
title_extention:                        J1 Video Apps
tagline:                                J1 Video Apps

date:                                   2020-11-04
#last_modified:                         2023-01-01

description: >
                                        J1 Template provides playing video on web pages
                                        by HTML5 Video and supports custom players created
                                        by VidoeJS to playback video individually.
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap,
                                        html, html5, video, support, flash player,
                                        quicktime, silverlight, videojs,
                                        vimeo, dailymotion, wistia, youtube

categories:                             [ Tour ]
tags:                                   [ Video, Module ]

image:
  path:                                 /assets/image/module/attic/1920x1280/modern-dance.jpg
  width:                                1920
  height:                               1280

compress:                               false
personalization:                        true
regenerate:                             false
permalink:                              /pages/public/tour/video_data/

resources:                              [ gallery, lightgallery, videojs ]

#resource_options:
#  - toccer:
#      collapseDepth:                    3
#  - attic:
#      slides:
#        - url:                          /assets/image/module/attic/1920x1280/modern-dance.jpg
#          alt:                          Photo Gemini AI

resource_options:
  - toccer:
      collapseDepth:                    3
  - attic:
      slides:
        - url:                          /assets/video/headers/present_videos/modern-dance.mp4
          alt:                          AI generated video
          title:                        Video Player
          tagline:                      Playback Video
          isVideo:                      true
          mute:                         false
#         loop:                         false
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:time-num--string:                      5-10
:time-en--string:                       Minutes
:time-en--description:                  to read
:time-de--string:                       Minuten
:time-de--description:                  Lesezeit

// Attribute settings for section control
//
:masonry:                               false
:justifiedGallery:                      true


//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
The J1 Template system supports playing video on web pages using native HTML5,
the current standard. Visitors can play video files without the need for an
external player.

Modern browsers support the video tag `<video>`. The previous proprietary
software, like _Flash Player_, _Quicktime_, _Silverlight_ is no longer required
as the J1 Template provides video support for local video files and online
sources.

[subs=attributes]
++++
<div class="video-title">
  <i class="mdib mdib-clock-outline mdib-24px mr-2"></i>
  {time-num--string} {time-en--string} {time-en--description}.
</div>
++++


// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== HTML 5 Video
// See: https://docs.asciidoctor.org/asciidoc/latest/macros/audio-and-video/
//
HTML5 video opens the doors to present local video content on your
website. All modern browsers support the video tag `<video>.` This Browsers
have a built-in multimedia framework for decoding and displaying video content.

Two types of video sources are supported:

* Video from local folders from your webspace
* Video from online sources like YouTube

Standalone video players embedded in websites are software components that
integrate and play video sources directly within a web page. These players
are essential for all current websites. Embedded players provide a seamless
and user-friendly way to present multimedia content to your audience.

[role="mb-4"]
All modern browsers universally support the video tag `<video>`. This tag
offers an out-of-the-box framework for decoding and displaying video content
without loading *external players*.

++++
<div class="video-title">
  <i class="mdib mdib-video mdib-24px mr-2"></i>
  Peck Pocketed · Local Video over HTML5 Video
</div>
++++

video::/assets/video//html5/peck_pocketed.mp4[poster="/assets/video/poster/html5/peck_pocketed.jpg", opts="" role="mt-1 mb-5"]

// video::179528528[vimeo] // doesn#'t work for current Vimeo Players
// video::RvRhUHTV_8k/PLDitloyBcHOm49bxNhvGgg0f9NRZ5lSaP[youtube]

[role="mt-5"]
== VideoJS

VideoJS is a *free-to-use* open-source JavaScript framework for building
custom video players for the web. Implementing VideoJS for J1 Template
supports *local video* and several *online platforms*, such as YouTube.

For *online sources*, VideoJS uses plugins, such as the so-called VJS
Playback Technology. With the help of *plugins*, it is possible to present
*different media* using the *same player*, the same look and feel for a
better user experience.

[role="mt-5"]
=== Local Video

VideoJS provides a flexible and customizable platform for MPEG4 video content
on web pages.

.Peck Pocketed · Local Video over VideoJS
videojs::/assets/video//html5/peck_pocketed.mp4[poster="/assets/video/poster/html5/peck_pocketed.jpg", opts="" role="mb-5"]

// .Rolling Wild · MP4 Video (over VideoJS)
// videojs::/assets/video//html5/rolling_wild.mp4[poster="/assets/video/poster/html5/rolling_wild.jpg", opts="" role="mb-5"]

[role="mt-5"]
=== YouTube

Today, YouTube is the most used online video-sharing platform that allows
users to upload, view, share, and comment on videos. YouTube provides services
for people and organizations to publish various video content on the internet.

Sky Elements uses the night sky as a canvas on which anything is possible.
A large group of Drones is painting lights in the sky to reflect the most
captivating narratives. 

.Sky Elements · AGT 2024 
youtube::brEXrQBIj68[poster="//img.youtube.com/vi/brEXrQBIj68/maxresdefault.jpg" role="mb-4"]


[role="mt-5"]
== Galleries of Video

Video galleries are collections that display videos organized around a
specific theme, topic, or purpose. The gallery module (lightGallery) for
J1 Template is a fast, modular, and responsive plugin for creating
beautiful-looking, featured image and video galleries.

The combination of a gallery and a lightbox is entirely usable for all
the video content you want to present on your site. You can place galleries
elsewhere with your content. You can use them for blogs by putting them into
your article's content. The galley maker *justifiedGallery* in combination
with the *lightbox* lightGallery is a great toolset for creating dynamic
video galleries. The module combinati0n makes creating a gallery to access
videos easy.

[role="mt-4"]
[CAUTION]
====
The module lightGallery can be used for free for private use, but a
*commercial license* is required for business or commercial websites. See
link:{url-light-gallery--license}[LightGallery Licenses, {browser-window--new}]
how to use lightGallery for *commercial* websites and projects.
====

Find below examples of video galleries of locally stored (MP4) video resources
*and* video content provided online.

[role="mt-4"]
[[justified-gllery-local-video]]
=== Local Video

Videos created by a digicam or a mobile can be played by J1 Template using
the lightGallery integration. Present videos you have made at it's best.

[role="mb-5"]
[NOTE]
====
The current file *size* of local video media files is limited to *50 MegaByte*.
Using a modern MP4 Encoder for video compression, a video will play around
*3-5 minutes* for HD 1080p (1920x1080 pixel) or up to *10 minutes* for
HD 720p (1280x720 pixel).
====

.Local MP4 Video · Justified Gallery + LightGallery
gallery::jg_video_html5[role="mb-4"]


[role="mt-5"]
[[justified-gllery-youtube]]
=== YouTube

The community at link:{url-youtube--home}[YouTube, {browser-window--new}]
is large, with over 1 billion users that watch hundreds of millions of
hours of content every day. The number of YouTube channels is enormous.
Today, it's a must for TV stations or musicians to publish videos of their
shows or songs on YouTube.

.YouTube Video · justifiedGallery + LightGallery
gallery::jg_video_youtube_james_and_adele[role="mb-4"]


[role="mt-5"]
== What next

Images and videos are pretty visual, and they can be impressive, for sure.
However, the most visual component on all web pages is text for all sites
on the Internet.

Sadly, one common flaw in many templates and frameworks is a lack of support
for *responsive text*. While other elements on a page resize fluidly, the
text is still fixed. To avoid this issue, especially for heavily text-focused
pages, the J1 Template supports a fluidly scaled text that changes
in size and line height to optimize readability for the user.

The JekyllOne Template J1 places the character font as one of the most crucial
*branding elements* for any website. Typography matters for any media presenting
text. The text will take on an important role of acting as plain text and as
something like images. To see how text could be presented is great for modern
responsive websites.

Find out how it works and go for link:{url-tour--typography}[Typography], then.
